import torch
import numpy as np

# int_tensor = torch.randint(0, 10, (3, 3), dtype=torch.int)
# float_tensor = torch.rand(3, 3)
# byte_tensor = torch.randint(0, 256, (3, 3), dtype=torch.uint8)
# long_tensor = torch.randint(0, 100, (3, 3), dtype=torch.long)
# print(int_tensor)
# print(int_tensor.type())
# print(float_tensor)
# print(float_tensor.type())
# print(byte_tensor)
# print(byte_tensor.type())
# print(long_tensor)
# print(long_tensor.type())
    # print(isinstance(long_tensor, torch.LongTensor))
# 检测是否在gpu上

# a = torch.tensor(1.3)
# print(a)
# print(a.shape)
# b = torch.FloatTensor(3, 3)
# print(b)
# c = torch.ones(2, 2)
# d = torch.zeros(2, 2)
# print(c)
# print(d)
# e = np.random.rand(5)
# e = torch.from_numpy(e)
# print(e)
# f = torch.full([2, 3], 8)
# print(f)
# g = torch.full([], 8)
# print(g)
    # h = torch.full([1], 8)
# print(h)

# a = torch.rand(4, 3, 2, 1)
# print(a.shape)
# print(a[:, 1, ...].shape)
# print(torch.numel(a))

# x = torch.rand(3, 4)
# print(x)
# mask = x.ge(0.5)
# print(mask)
# y = torch.masked_select(x, mask)
# print(y)
